### ISSUE TITLE
Feature: Config Management

### ISSUE THREAD

**Issue by tada5hi** [authup/authup#1591]
Top Level Keys: 

**InHouse Services**
- core (server-core)
  - env
  - rootPath
  - writableDirectoryPath
  - port
  - log (level, format, filePath)
  - host
  - publicUrl
  - authorizeRedirectUrl
  - redis 
  - db
  - vault
  - email/smtp
  - ntp (server, version)
  - toptp (issuer, algorithm, period, digits)
  - tokenAccessMaxAge
  - tokenRefreshMaxAge
  - registration
  - emailVerification
  - forgotPassword
  - adminUsername
  - adminPassword
  - adminPasswordReset
  - robotEnabled
  - robotSecret
  - robotSecretReset
  - permissions
- realtime (server-realtime)
   - env
   - rootPath
   - writableDirectoryPath
   - port
   - host
   - log (level, format, filePath)
   - publicUrl
   - apiUrl
   - redis
- web 
   - env
   - rootPath
   - writableDirectoryPath
   - port
   - host
   - publicUrl
   - apiUrl
   - realtimeUrl

**Comment by Jogai** [comment]
How can we set the correct api url when running the containers? What I tried so far is this with compose, but apiUrl keeps pointing to 127.0.0.1. This is my compose yaml:

```
services:
    authup-be:
      image: ghcr.io/authup/authup:1.0.0
      container_name: authup-be
      command: server/core start
      volumes:
        - /home/server/authup:/usr/src/writable

    authup-fe:
      image: ghcr.io/authup/authup:1.0.0
      container_name: authup-fe
      environment: 
        - API_URL="http://authup-be:3001" 
      command: client/web start
      env_file:
        - .env

**Comment by tada5hi** [comment]
@Jogai i updated the public docs.
You need to prefix the environment variables for the frontend application with `NUXT_PUBLIC_`.

```yml
version: '3.8'

volumes:
    authup:

services:
  server-core:
      image: ghcr.io/authup/authup:latest
      container_name: server-core
      restart: unless-stopped
      volumes:
        # Docker managed volume
        - authup:/usr/src/writable
        # storage in mounted volume
        #- ./writable:/usr/src/writable
      ports:
        - "3001:3000"
      command: server/core start

  client-web:
      image: ghcr.io/authup/authup:latest
      container_name: client-web
      restart: unless-stopped
      environment:
        - NUXT_PUBLIC_API_URL=http://localhost:3001 #optional
        - NUXT_PUBLIC_PUBLIC_URL=http://localhost:3000 #optional
      volumes:
          # Docker managed volume
          - authup:/usr/src/writable
          # storage in mounted volume
          #- ./writable:/usr/src/writable
      ports:
          - "3000:3000"
      command: client/web start
```

PS: You should maybe use `NUXT_PUBLIC_API_URL=http://localhost:3001/`, since the alias authup-be is only available for your docker containers but not your browser.

**Comment by Jogai** [comment]
Thanks, that works (and the info was here all along: https://authup.org/guide/deployment/configuration-client-web.html). 

But now I get: `Response body is not available to scripts (Reason: CORS Allow Origin Not Matching Origin)` both in firefox and chrome for the calls to `identity-providers`, `realms` and `token` (POST request). 

By now my yaml look like this:

```
services:
  authup-core:
      image: ghcr.io/authup/authup:latest
      container_name: authup-core
      volumes:
        - /home/server/authup:/usr/src/writable
      environment:
        - ADMIN_USERNAME=admin
        - ADMIN_PASSWORD=********
        - PUBLIC_URL=proxy-url-to-core
        - AUTHORIZE_REDIRECT_URL=proxy-url-to-web
      command: server/core start

  authup-web:
      image: ghcr.io/authup/authup:latest
      container_name: authup-web
      environment:
        - NUXT_PUBLIC_API_URL=proxy-url-to-core
        #- NUXT_PUBLIC_PUBLIC_URL=proxy-url-to-web
      volumes:
          - /home/server/authup:/usr/src/writable
      command: client/web start
```

My proxy handles the port-mapping, so my web url shows the web login, and the other one shows `{"version":"1.0.0-beta.2","timestamp":1706343657007,"tokenMaxAgeAccessToken":3600,"tokenMaxAgeRefreshToken":7200,"redis":false,"vault":false}`.

It feels like I'm still missing something small, so if you could give me a hint?
